[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = ["echo 'Build phase - dependencies already installed'"]

[phases.start]
cmd = "cd backend && node server.js"

[variables]
NODE_ENV = "production"
