services:
  # Backend API
  - type: web
    name: resona-backend
    env: node
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      # IMPORTANT: You need to replace this with your actual MongoDB Atlas connection string
      - key: MONGO_URL
        value: mongodb+srv://username:password@cluster.mongodb.net/resona?retryWrites=true&w=majority
      - key: BCRYPT_ROUNDS
        value: 12
      - key: MAX_FILE_SIZE
        value: 10485760

  # Frontend React App  
  - type: web
    name: resona-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: resona-backend
          property: host
      - key: VITE_APP_NAME
        value: Resona Music Platform
