services:
  # Backend API
  - type: web
    name: resona-backend
    env: node
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Your existing JWT secret - already secure!
      - key: JWT_SECRET
        value: 970797bc2b8d6c757dda53bbe6717554d0737d8b7b9ec0218487e16eecd78fe2d2099a0760e13c5424fb67ebad8e6966afa8d467a8dc71fa885b18556f4141e6
      # Your existing MongoDB Atlas connection - already working!
      - key: MONGO_URL
        value: mongodb+srv://pranavpriyadarshi903:RdwlX7HHY9OJFS1g@cluster0.zdus30v.mongodb.net/resona_music_player?retryWrites=true&w=majority
      - key: BCRYPT_ROUNDS
        value: 12
      - key: MAX_FILE_SIZE
        value: 10485760

  # Frontend React App  
  - type: web
    name: resona-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: resona-backend
          property: host
      - key: VITE_APP_NAME
        value: Resona Music Platform
